import Head from 'next/head'
import Image from 'next/image'
import { css, cx } from '@emotion/react'
import { motion } from "framer-motion"
import { Grid, GridItem } from "@chakra-ui/react"
import { Heading } from "@chakra-ui/react"
import { Box } from "@chakra-ui/react"
import Link from 'next/link'
import styles from "@styles/Feedback.module.css";
import { extendTheme } from '@chakra-ui/react'
import { createBreakpoints } from '@chakra-ui/theme-tools'
import { Button, ButtonGroup } from "@chakra-ui/react"
import {
    Modal,
    ModalOverlay,
    ModalContent,
    ModalHeader,
    ModalFooter,
    ModalBody,
    ModalCloseButton,
  } from "@chakra-ui/react"
import CreatePost from '@component/create-post'
import { Textarea } from '@chakra-ui/react'
import PostMain from '@component/post-main'
import PostCritiques from '@component/post-critiques'
// import { Image } from '@chakra-ui/react'

const breakpoints = createBreakpoints({
    sm: '320px',
    md: '768px',
    lg: '960px',
    xl: '1200px',
    '2xl': '1536px',
  })

const theme = extendTheme({ breakpoints })

export default function CritiquePost(){
    return(
        <>
        <main className={styles.container}>
            <Head>
            <title>Critique Post</title>
            <meta name="description" content="Critique Hall generated by Next App" />
            <link rel="icon" href="/logo256.png" onLoad=""/>
            </Head>

            <Box w="100%" h="full" spacing="10px" mt="5">
                <Box display="flex" p="3">
                    {/* Main */}
                    <PostMain />
                    {/* Critique */}
                    <PostCritiques />
                </Box>
            </Box>

        </main>

        
        
        </>
    )
}