import Head from 'next/head'
import Image from 'next/image'
import { css, cx } from '@emotion/react'
import { motion } from "framer-motion"
import { Grid, GridItem } from "@chakra-ui/react"
import { Heading } from "@chakra-ui/react"
import { Box } from "@chakra-ui/react"
import Link from 'next/link'
import styles from "@styles/Feedback.module.css";
import { extendTheme } from '@chakra-ui/react'
import { createBreakpoints } from '@chakra-ui/theme-tools'
import { Button, ButtonGroup } from "@chakra-ui/react"
import {
    Modal,
    ModalOverlay,
    ModalContent,
    ModalHeader,
    ModalFooter,
    ModalBody,
    ModalCloseButton,
  } from "@chakra-ui/react"



function CreatePost() {
    return(
        <main className={styles.container}>
            <Head>
            <title>Create Post</title>
            <meta name="description" content="Critique Hall generated by Next App" />
            <link rel="icon" href="/logo256.png" onLoad=""/>
            </Head>

            <Box display="flex" w="100%" spacing="10px" top="0" h="100%" >
                <Box w={{lg: "70%" , sm: '100%'}} bg="white" mx="auto" h="80vh" p="3" boxShadow="lg">
                    <Heading mx="auto">Hi</Heading>
                </Box>
            </Box>
        </main>
        
    )

}

export default CreatePost