import Head from 'next/head'
import Image from 'next/image'
import { css, cx } from '@emotion/react'
import { motion } from "framer-motion"
import { Button, Center, Heading } from '@chakra-ui/react'
import Link from 'next/link'
import {
    Modal,
    ModalOverlay,
    ModalContent,
    ModalHeader,
    ModalFooter,
    ModalBody,
    ModalCloseButton,
  } from "@chakra-ui/react"
import { Box } from '@chakra-ui/react'
import { Grid, GridItem } from '@chakra-ui/react'
import Pagination from 'react-js-pagination'
import styles from '@styles/Search.module.css'



export default function SearchResult(){

    return(
        <div className={styles.container}>

            <Head>
                <title>Search Results for</title>
                <meta name="description" content="Critique Hall generated by Next App" />
                <link rel="icon" href="/logo256.png" onLoad=""/>
            </Head>
            <Box w="100%" mb="10" mt="15vh">
                <Heading><Center>Search Result for</Center></Heading>
            </Box>
            {/* <Pagination></Pagination> */}
            {/* Search Item */}
            <Box w={{lg: '70%', sm: '100%'}} display={{lg: 'flex', sm: 'block'}} mt='2ch' mx="auto">
                <Box p="3" w="100%" bg="light">
                            Hall
                        </Box>
                        <Box p="3" w="100%" bg="light">
                            Image
                        </Box>
                        <Box p="3" w="100%" bg="light">
                            Title
                        </Box>
                        <Box p="3" w="100%" bg="light">
                            Posted by:
                        </Box>
                        <Box p="3" w="100%" bg="light" display='flex'>
                            <Box w="100%" bg="light">
                                Time
                            </Box>
                            <Box w="100%" bg="light">
                                Options
                            </Box>      
                        </Box>       
            </Box>


        </div>
    )


};
