import Head from 'next/head'
import Image from 'next/image'
import { css, cx } from '@emotion/react'
import { motion } from "framer-motion"
import { Box, Button, Flex, Heading, Spacer, Text } from '@chakra-ui/react'
import Link from 'next/link'
import {
    Modal,
    ModalOverlay,
    ModalContent,
    ModalHeader,
    ModalFooter,
    ModalBody,
    ModalCloseButton,
  } from "@chakra-ui/react"
import EditProfile from '@component/edit-profile'
import styles from '@styles/Profile.module.css'

export default function ProfilePage() {

    return(
        <main className={styles.container}>

            <Head>
                <title>User</title>
                <meta name="description" content="Critique Hall generated by Next App" />
                <link rel="icon" href="/logo256.png" onLoad=""/>
            </Head>

            <Box mx='auto' my='auto' bg='blue.200' w='90%' h='80vh' rounded='lg' mt={32} position='static'>
                <Box display='flex' flexDir='row'>
                    <Box w='100vh' h='35vh' bg='white' p={3} mt={5} ml={5} rounded='lg'>
                        <Box w='20vh' h='20vh' bg='gray' mt={24} ml={5} rounded='full'></Box>
                        
                    </Box>
                    <Box w='70vh' h='35vh' bg='blue.500' p={3} mt={5} ml={8} rounded='lg'>
                        <Flex>
                        <Heading size='2xl' as='h3' color='white' mt={10}>About Me: </Heading>
                        <Spacer />
                            <EditProfile/>
                        </Flex>
                        <Text w='65vh' fontSize='md' color="white">LoremMinim eu pariatur enim laborum. Excepteur veniam voluptate dolor voluptate dolor officia et ea commodo cupidatat consequat officia in. Dolor laboris mollit exercitation proident commodo quis aute enim laboris. </Text>
                        <Heading size='md' color='white' mt={5}>Reputation Points: </Heading>
                        <Heading size='md' color='white' mt={5}>Strand/Specialization: </Heading>
                    </Box>
                </Box>
                <Box display='flex' w='30%' mt={5}>
                    <Button ml={5} h='2em' position='static'>All</Button>
                    <Button ml={5} h='2em' position='static'>My Posts</Button>
                    <Button ml={5} h='2em' position='static'>My Critiques</Button>
                </Box>
                <Box display='flex' h='35vh' p={3} mt={5} ml={3} w='98%' rounded='lg'>

                </Box>
            </Box>
        </main>
    )


};
