import Head from 'next/head'
import Image from 'next/image'
import styles from "@styles/ForgotPassword.module.css";
import { css, cx } from '@emotion/react'
import { motion } from "framer-motion"
import Home from './home'
import Link from 'next/link'
import Logo from "@public/critiquehall2.png";
import { Heading } from '@chakra-ui/react'
import { Box } from "@chakra-ui/react"
import { Button, ButtonGroup } from "@chakra-ui/react"
import { Stack, HStack, VStack } from "@chakra-ui/react"
import {
  FormControl,
  FormLabel,
  FormErrorMessage,
  FormHelperText,
} from "@chakra-ui/react"
import {
  Popover,
  PopoverTrigger,
  PopoverContent,
  PopoverHeader,
  PopoverBody,
  PopoverFooter,
  PopoverArrow,
  PopoverCloseButton,
} from "@chakra-ui/react"
import { useState } from 'react'
import { useColorModeValue } from '@chakra-ui/react';
import { createBreakpoints } from '@chakra-ui/theme-tools'
import axios from "axios"
import { useCookies } from 'react-cookie';


const breakpoints = createBreakpoints({
  sm: '320px',
  md: '768px',
  lg: '960px',
  xl: '1200px',
  '2xl': '1536px',
})


const MotionButton = motion(Button)

export default function ConfirmationPage(){
  const { API_URL } = process.env
  const { API_KEY } = process.env

  const [code, setCode] = useState('')
  const [cookies, setCookies, removeCookies] = useCookies(['token', 'id', 'encrypted_id'])

  const forgotPassword = async () =>{

        let formData = new FormData(); 
        formData.append('verification_code', code);
        
        const config = {
          headers: { 
            'content-type': 'multipart/form-data',
            'X-API-KEY': `${API_KEY}`,
            'Authorization': 'Basic Y2Fwc3RvbmUyMDIxOjEyMzQ=',
            // 'Accept-Encoding': 'gzip, deflate, br',
            'Accept': 'application/json',
            'user_id': cookies.encrypted_id
          }
        }

        // console.log(email)
  
        axios.post(`${API_URL}/api/confirm_verification`, formData, config)
        .then(response => {
            console.log(response);
            setCookies('token', response.data.token)
            window.location = "/home"
        })
        .catch(error => {
            console.log(error.response);
        });
    }

    return(
        <div className={styles.container} >
        <Head>
          <title>Confirm Verification</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/logo256.png" onLoad=""/>
        </Head>
        
        <Box className={styles.main} bg={useColorModeValue('white', '#1a202c')} w={{lg: '100ch' , md: '100%' , sm: '100%' }} >
            <center>
            <div className={styles.logo}>
            <Link href="/" passHref><Image src={Logo} alt="Critique Hall Logo"></Image></Link>
            </div>

            <Heading mb={2} as="h2" size="lg" color={useColorModeValue('#1B1464')}>Confirmation</Heading>
            <p className={styles.description}>Kindly enter the verification code to verify your account</p>
            <center><FormControl id="forgotpassword" isRequired>
                <input placeholder="" className={styles.input_box} type="text" value={code} onChange={e => setCode(e.target.value)}/>
                <FormHelperText className={styles.helperText}>This field is required.</FormHelperText>
                <br/>
                <MotionButton
                  whileHover={{ scale: 1.2 }}
                  whileTap={{ scale: 0.9 }}
                  className={styles.login_button}
                  colorScheme="messenger"
                  size="lg"
                  onClick={forgotPassword}
                  >
                Submit
                </MotionButton>
                {/* <Popover
                placement="bottom"
                closeOnBlur={false}>
                <PopoverTrigger>
                
                </PopoverTrigger>
                <PopoverContent color="white" bg="blue.800" borderColor="blue.800">
                <PopoverArrow />
                <PopoverCloseButton />
                <PopoverHeader pt={4} fontWeight="bold" border="0">Reset Password Link Sent!</PopoverHeader>
                <PopoverBody>We have sent a reset password confirmation to your e-mail.
                  Check on your primary or spam folder.
                </PopoverBody>
                </PopoverContent>
                </Popover> */}
            </FormControl></center>

            {/* <p className={styles.register}>
              <p><Link href="./login"><a>Back to Login</a></Link></p>
            </p> */}
            </center>

        </Box>
        </div>
    )
}
