import Head from 'next/head'
// import Image from 'next/image'
import { Center, Image } from '@chakra-ui/react'
import { css, cx } from '@emotion/react'
import { motion } from "framer-motion"
import Layout from './layout/layout'
import styles from "@styles/Home.module.css";
import { Box, Divider } from "@chakra-ui/react"
import { Spacer } from "@chakra-ui/react"
import { Heading } from '@chakra-ui/react'
import { extendTheme } from '@chakra-ui/react'
import { createBreakpoints } from '@chakra-ui/theme-tools'
import { Button, ButtonGroup } from "@chakra-ui/react"
import { ChevronDownIcon } from '@chakra-ui/icons'
import {
    Menu,
    MenuButton,
    MenuList,
    MenuItem,
    MenuItemOption,
    MenuGroup,
    MenuOptionGroup,
    MenuIcon,
    MenuCommand,
    MenuDivider,
    Flex
  } from '@chakra-ui/react'
import Logo from "@public/critiquehall.png";
import ArtBanner from "@public/Arts.png";
import BusinessBanner from "@public/Business.png";
import LoungeBanner from "@public/Lounge.png";
import TechnologyBanner from "@public/Technology.png"; 
import { useRouter } from "next/router";
import { useCookies } from 'react-cookie'
import { storage } from '../firebase.js'
import { getDownloadURL, ref, uploadBytesResumable } from 'firebase/storage'
import {useState} from 'react'
import ShowHallDescription from '@component/show-hall-description'
import { useColorModeValue } from "@chakra-ui/react";


const breakpoints = createBreakpoints({
    sm: '320px',
    md: '768px',
    lg: '960px',
    xl: '1200px',
    '2xl': '1536px',
  })

const theme = extendTheme({ breakpoints })

function Home(){

    

    return( 
        <main className={styles.container} w="100%">
          <Head>
            <title>Critique Hall | Home</title>
            <meta name="description" content="Critique Hall generated by Next App" />
            <link rel="icon" href="/logo256.png" onLoad=""/>
          </Head>

          <Box position='static' bgColor={useColorModeValue('#E5E5E5', '#2E2E2E')} w="100%" h={{lg: '75vh', md: '100%', sm: '100%'}} display={{lg: 'flex', md: 'flex', sm: 'block'}} z-index='-1' boxShadow='lg' borderBottom="1px solid black">
          <Flex mt={44} flexDir='column' align='center' w={{lg: '50vw', md: '100%', sm: '100%'}}>
              <Heading size='3xl' >WELCOME TO</Heading>
              <Image src='critiquehall.png' w={{lg: '500px', md: '500px', sm: '500px'}} h='37vh' mt={5}/>
              {/* <Link href="/login"><Button type='submit' mt={5} colorScheme='red' position='static'>Get Started</Button></Link> */}
            </Flex>
            <Image src='man-texting.png' w={{lg: '600px', md: '600px', sm: '600px'}} h='60vh' mt='10vh' mb='5vh' mr='10vw' align='center' />
          </Box>

            {/* <form onSubmit={formHandler}>
              <input type='file' />
              <Button type='submit' />
            </form>
            <h3>Uploaded {progress} %</h3> */}

          <Box position='static' bgColor={useColorModeValue('#EFEFEF', '#242424')} w="100%" h="100%" display={{lg: 'flex', md: 'flex', sm: 'block'}} boxShadow='lg' borderBottom="1px solid black">
            <Flex flexDir={{lg: 'row', md: 'row', sm: 'column'}} >
              <Flex w={{lg: '45vw', md: '100%', sm: '100%'}}>
              <Image src='discussions.png' w={{lg: '700px', md: '700px', sm: '700px'}} h='60vh' mt='10vh' ml='7vw' align='center'/>
              </Flex>
              <Spacer />
              <Flex mt={16} flexDir='column' align='center' w={{lg: '45vw', md: '100%', sm: '100%'}}>
                <Heading size='3xl'>WHAT IS</Heading>
                
                <Flex flexDir={{lg: 'row', md: 'row', sm: 'column'}}>
                  <Image src='critiquehall.png' w={{lg: '500px', md: '500px', sm: '500px'}} h='37vh' mt={5}/>
                  <Heading size='3xl' my='auto' mx={{lg: '0', md: '0', sm: 'auto'}}>?</Heading>
                </Flex>
                <Heading size='xl' w={{lg: '30vw', md: '100%', sm: '100%'}} align='center' mt={5} mb={10}>An Open Forum Web Application for Students and Teachers</Heading>
              </Flex>
            </Flex>
          </Box>

          {/* <Divider position='static' /> */}

          <Box position='static' bgColor={useColorModeValue('#E5E5E5', '#2E2E2E')}  w="100%" h="100%" display={{lg: 'flex', md: 'flex', sm: 'block'}} boxShadow='lg' borderBottom="1px solid black">

            <Flex flexDir={{lg: 'row', md: 'row', sm: 'column'}} >
              <Flex mt={16} flexDir='column' align='center' w={{lg: '45vw', md: '100%', sm: '100%'}}>
                <Heading size='3xl' >GOAL OF</Heading>
                <Image src='critiquehall.png' w={{lg: '500px', md: '500px', sm: '500px'}} h='37vh' mt={5}/>
              </Flex>
              <Spacer />
              <Flex flexDir="column" mt={{lg: 16, md: 5, sm: 5}} w={{lg: '45vw', md: '100%', sm: '100%'}}>
                <Heading size='lg' w={{lg: '45vw', md: '100%', sm: '100%'}} align='center'>To meet the student and teacher’s needs with regards to academic lives and personal development.</Heading>
                <Image src='SOB.png' w={{lg: '900px', md: '900px', sm: '900px'}} h='60vh' mt='-2vh' mr='20vw' align='center'/>
              </Flex>
            </Flex>
              
          </Box>

          {/* <Divider position='static' /> */}

          <Box position='static' boxShadow='lg' w="100%" h="80vh" display={{lg: 'flex', md: 'flex', sm: 'block'}} flexDir='column'>
            <Heading size='3xl' align='center' w='100%' mt={5}>Halls</Heading>
            <Flex mt='10vh' w={{lg: '90%', md: '100vw', sm: '100vw'}} mx='auto' overflowX='auto'>
              <Box w={{lg: '20vw', md: '100%', sm: '100%'}} h='40vh' bg='purple'>
                <Heading align='center' mt={5} color='white' >Technology</Heading>
                <Center>
                  <Image src='SOC.png' alt='School of Computing' align='center' w='10vw' h='20vh' mt={5}/>
                </Center>
                <Center mt='10'>
                  <ShowHallDescription hall='Technology' color='#bd01bd' fontColor='white' />
                </Center>
              </Box>
              <Spacer />
              <Box w={{lg: '20vw', md: '100%', sm: '100%'}} h='40vh' bg='blue.300' ml={{lg: '0', md: '0', sm: '20vw'}}>
                <Heading align='center' mt={5} color='white'  >Arts</Heading>
                <Center>
                  <Image src='SODA.png' alt='School of Design and Arts' align='center' w='20vw' h='20vh' mt={5}/>
                </Center>
                <Center mt='10'>
                  <ShowHallDescription hall='Arts' color='#91c9f2' fontColor='black' />
                </Center>
              </Box>
              <Spacer />
              <Box w={{lg: '20vw', md: '100%', sm: '100%'}} h='40vh' bg='red'>
                <Heading align='center' mt={5} color='white' >Business</Heading>
                <Center>
                  <Image src='SOB.png' alt='School of Business' align='center' w='20vw' h='20vh' mt={5}/>
                </Center>
                <Center mt='10'>
                  <ShowHallDescription hall='Business' color='#ff5656' fontColor='black'/>
                </Center>
              </Box>
              <Spacer />
              <Box w={{lg: '20vw', md: '100%', sm: '100%'}} h='40vh' bg='green.300'>
                <Heading align='center' mt={5} color='white' >Lounge</Heading>
                <Center>
                  <Image src='discussions.png' alt='Lounge' align='center' w='15vw' h='20vh' mt={5}/>
                </Center>
                <Center mt='10'>
                  <ShowHallDescription hall='Lounge' color='#9affc0' fontColor='black'/>
                </Center>
              </Box>
            </Flex>
          </Box>  

        </main>
    )
}

export default Home

