import Head from 'next/head'
import Image from 'next/image'
import { css, cx } from '@emotion/react'
import { motion } from "framer-motion"
import Layout from './layout/layout'
import styles from "@styles/Home.module.css";
import { Box } from "@chakra-ui/react"
import { Spacer } from "@chakra-ui/react"
import { Heading } from '@chakra-ui/react'
import { extendTheme } from '@chakra-ui/react'
import { createBreakpoints } from '@chakra-ui/theme-tools'
import { Button, ButtonGroup } from "@chakra-ui/react"
import { ChevronDownIcon } from '@chakra-ui/icons'
import {
    Menu,
    MenuButton,
    MenuList,
    MenuItem,
    MenuItemOption,
    MenuGroup,
    MenuOptionGroup,
    MenuIcon,
    MenuCommand,
    MenuDivider,
  } from '@chakra-ui/react'

const breakpoints = createBreakpoints({
    sm: '320px',
    md: '768px',
    lg: '960px',
    xl: '1200px',
    '2xl': '1536px',
  })

const theme = extendTheme({ breakpoints })

// export const getStaticProps = async () => {
//     const res = await fetch (`https://jsonplaceholder.typicode.com/posts`)
//     const articles = await res.json()

//     return{
//         props:{
//             articles
//         }
//     }
// }


export default function Home(){
    return(
        <main className={styles.container} w="100%">
        <Head>
        <title>Home</title>
        <meta name="description" content="Critique Hall generated by Next App" />
        <link rel="icon" href="/logo256.png" onLoad=""/>
        </Head>
        <Box w={{lg: '70%', md: "70%", sm: '100%'}} mt="5">
            <Heading size='md'>Latest Posts</Heading>
            <Box w="full" mt="3" h="15vh" overflow="hidden" p="5">
                <div>Hi</div>
            </Box>

        </Box>

        <Box display={{lg: 'flex', sm: 'block'}} className={styles.flexcard1} w={{lg: '70%', md: "70%", sm: '100%'}} top="0" h="100%" mt="5">
            <Box width={{lg: '70%', md: "80%", sm: '100%'}} bg="white" h="500vh"  p="3" boxShadow="lg" >
                <Heading size='lg' >Popular Posts</Heading>
                <Box mt="3" display={{lg: 'block', md: 'block', sm: 'none'}}>
                <button className={styles.button1}>Hot</button>
                <button className={styles.button2}>New</button>
                <button className={styles.button3}>Top</button>
                <button className={styles.button4}>Rising</button>
                </Box>
                {/* {articles.map(article => (
                    <span>{article.id}</span>,
                    <h3>{article.title}</h3>
                ))} */}
                <Box mt="3" w="80%" borderColor="gray" border="1px solid gray" borderRadius="md" display={{lg: 'none', md: 'none', sm: 'block'}}>
                <Menu>
                    <MenuButton
                        px={4}
                        py={2}
                        transition='all 0.2s'
                        w="100%"
                        // borderRadius='md'
                        // borderWidth='1px'
                        // _hover={{ bg: 'gray.400' }}
                        // _expanded={{ bg: 'blue.400' }}
                        // _focus={{ boxShadow: 'outline' }}
                    >
                        
                        Hot 

                        {/* <ChevronDownIcon /> */}
                    </MenuButton>
                    <MenuList>
                        <MenuItem>Hot</MenuItem>
                        <MenuItem>New</MenuItem>
                        <MenuItem>Top</MenuItem>
                        <MenuItem>Rising</MenuItem>
                    </MenuList>
                    </Menu>
                </Box>
                
            </Box>
            <Box display={{lg: 'block', md: 'block', sm: 'none'}} width={{lg: '28.3%', md: "40%", sm: '100%'}} mt={{lg: 0, sm: '10px'}} h="50vh" bg="white" p="3" boxShadow="lg" ml={{lg: '30px'}} >
                <Heading size='lg'>Top Halls</Heading>
            </Box>
        </Box>

        

        
            
        </main>
    )
}

