import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { motion } from "framer-motion"
import Link from 'next/link'

const variants = {
  visible: { opacity: 1 },
  hidden: { opacity: 0 },
}


export default function Home() { 
  return (
    <div className={styles.container}>
      <Head>
        <title>Welcome to Critique Hall</title>
        <meta name="description" content="Critique Hall generated by Next App" />
        <link rel="icon" href="/logo256.png" onLoad=""/>
      </Head>

      <main className={styles.main}>

        <motion.h1 
          animate={{ y: 50, stdDeviation: [1, 5, 3], opacity:1}}
          initial="hidden"
          variants={variants}
          className={styles.title}>
          <img src="/critiquehall2.png" />
        </motion.h1>

        <motion.p 
          initial="hidden" 
          animate="visible" 
          variants={variants} 
          className={styles.description}>
          A Discussion Forum Web Application for Students
        </motion.p>

        <button className={styles.getStartedButton}>
          <motion.span
            // animate={{opacity:1}}
            initial={{opacity:0.5}}
            whileHover={{opacity:1}}
            transition={{duration:.1}}
          >
          <Link href="/login">Get Started</Link>
          </motion.span>
        </button>

      </main>
    </div>
  )
}