import Head from 'next/head'
import styles from "@styles/Welcome.module.css";
import { motion } from "framer-motion"
import Link from 'next/link'
import { Stack, HStack, VStack, useColorMode, FormLabel, Input, Textarea } from "@chakra-ui/react"
import { Button, ButtonGroup } from "@chakra-ui/react"
import { ArrowForwardIcon, CheckIcon, InfoOutlineIcon } from '@chakra-ui/icons'
import { Box, Divider, Flex, Heading, Spacer, Image } from "@chakra-ui/react"
import axios from 'axios';
import {useState} from 'react';
import ManTexting from "@public/man-texting.png";


const variants = {
  visible: { opacity: 1 },
  hidden: { opacity: 0 },
}

const imageLoader = ({ src, width, quality }) => {
  return `/${src}?=${width}&q=${quality || 100}`
}

const MotionButton = motion(Button)

export default function Welcome() {
  const { API_URL } = process.env
  const { API_KEY } = process.env

  const [email, setEmail] = useState('')
  const [fullName, setFullName] = useState('')
  const [subject, setSubject] = useState('')
  const [message, setMessage] = useState('')

  const sendMessage = () =>{

      let formData = new FormData(); 
      formData.append('email', email);   //append the values with key, value pair
      formData.append('full_name', fullName);
      formData.append('subject', subject);
      formData.append('message', message);

      const config = {
        headers: { 
          'content-type': 'multipart/form-data',
          'X-API-KEY': `${API_KEY}`,
          'Authorization': 'Basic Y2Fwc3RvbmUyMDIxOjEyMzQ=',
          'Accept': 'application/json',
        }
      }

      axios.post(`${API_URL}/api/email_suggestion`, formData, config)
      .then(response => {
          console.log(response.data);
          window.location.href = "/"
      })
      .catch(error => {
          console.log(error);
      });

  }
  
  

  return (
    <div className={styles.container}>
      <Head>
        <title>Welcome to Critique Hall</title>
        <meta name="description" content="Critique Hall generated by Next App" />
        <link rel="icon" href="/logo256.png" onLoad=""/>
      </Head>



      <Box position='static' w="100%" h="70vh" display={{lg: 'flex', md: 'flex', sm: 'block'}} z-index='-1' borderBottom="1px solid black">
            <Flex mt={44} flexDir='column' align='center' w={{lg: '50vw', md: '100%', sm: '100%'}}>
              <Heading size='3xl' >WELCOME TO</Heading>
              <Image src='critiquehall.png' w={{lg: '30vw', md: '100%', sm: '100%'}} h='37vh' mt={5}/>
              <Link href="/login"><Button type='submit' colorScheme='red'>Get Started</Button></Link>
            </Flex>
            
          </Box>

          <Box position='static' w="100%" h="70vh" display={{lg: 'flex', md: 'flex', sm: 'block'}} borderBottom="1px solid black">
            <Flex flexDir={{lg: 'row', md: 'row', sm: 'column'}} >
              <Flex w='45vw'>

              </Flex>
              <Spacer />
              <Flex mt={16} flexDir='column' align='center' w={{lg: '45vw', md: '100%', sm: '100%'}}>
                <Heading size='3xl'>WHAT IS</Heading>
                <Flex flexDir={{lg: 'row', md: 'row', sm: 'column'}}>
                  <Image src='critiquehall.png' w={{lg: '30vw', md: '100%', sm: '100%'}} h='37vh' mt={5}/>
                  <Heading size='3xl' my='auto' mx={{lg: '0', md: '0', sm: 'auto'}}>?</Heading>
                  
                </Flex>
                <Heading size='xl' w={{lg: '30vw', md: '100%', sm: '100%'}} align='center' mt={5}>An Open Forum Web Application for Students and Teachers</Heading>
              </Flex>
            </Flex>
              
          </Box>

          {/* <Divider position='static' /> */}

          <Box position='static' w="100%" h="70vh" display={{lg: 'flex', md: 'flex', sm: 'block'}} borderBottom="1px solid black">

            <Flex flexDir={{lg: 'row', md: 'row', sm: 'column'}} >
              <Flex mt={16} flexDir='column' align='center' w={{lg: '45vw', md: '100%', sm: '100%'}}>
                <Heading size='3xl' >GOAL OF</Heading>
                <Image src='critiquehall.png' w={{lg: '30vw', md: '100%', sm: '100%'}} h='37vh' mt={5}/>
              </Flex>
              <Spacer />
              <Flex mt={{lg: 16, md: 5, sm: 5}} w={{lg: '45vw', md: '100%', sm: '100%'}}>
                <Heading size='lg' w={{lg: '45vw', md: '100%', sm: '100%'}} align='center'>To meet the student and teacher’s needs with regards to academic lives and personal development.</Heading>
              </Flex>
            </Flex>
              
          </Box>


          {/* <Divider position='static' /> */}

          <Box position='static' w="100%" h="80vh" display={{lg: 'flex', md: 'flex', sm: 'block'}}>
            <Flex flexDir='column' w='100%'>
            <Flex flexDir='column' w='100%'>
              <Heading size='4xl' align='center' w='100%' mt={5}>WE'D LOVE TO HEAR FROM YOU</Heading>
              <Heading size='lg' align='center' w='100%' mt={5}>Send your feedbacks and suggestions and we’ll answer it for you.</Heading>
            </Flex>
            <form action='' method='POST'>
              <Flex w='100%' flexDir={{lg: 'row', md: 'row', sm: 'column'}} align='center'  mt={20}>
                <Box w='30vw'>

                </Box>
              
                <Flex flexDir='column' w='100%' align='center'>
                
                  <Flex align='center' flexDir={{lg: 'row', md: 'row', sm: 'column'}} w={{lg: '40vw', md: '40vw', sm: '100%'}} color='black'>
                      <Input type='text' w={{lg: '13vw', md: '13vw', sm: '100%'}} placeholder='Email Address' onChange={(e)=>setEmail(e.target.value)}></Input>
                      <Spacer />
                      <Input type='text' w={{lg: '13vw', md: '13vw', sm: '100%'}} mt={{lg: 0, md: 0, sm: 5}} placeholder='Full Name' onChange={(e)=>setFullName(e.target.value)}></Input>
                      <Spacer />
                      <Input type='text' w={{lg: '13vw', md: '13vw', sm: '100%'}} mt={{lg: 0, md: 0, sm: 5}} placeholder='Subject' onChange={(e)=>setSubject(e.target.value)}></Input>
                  </Flex>
                  <Textarea w={{lg: '40vw', md: '40vw', sm: '100%'}} h='20vh' mt={5} placeholder='Message...' mt={{lg: 0, md: 0, sm: 5}} onChange={(e)=>setMessage(e.target.value)} />
                
                </Flex>
                <Flex w={{lg: '20vw', md: '100%', sm: '100%'}} mt={{lg: 0, md: 0, sm: 5}} >
                  <Button colorScheme='blue' w={{lg: '10vw', md: '20vw', sm: '20vw'}} mr={{lg: 48, md: 0, sm: 0}} mx={{lg: 0, md: 0, sm: 'auto'}} onClick={sendMessage} >Submit</Button>
                </Flex>
              </Flex>
              </form>
            </Flex>
            
              
          </Box> 


      {/* <div className={styles.main}>

      </div>
      <div className={styles.main}>
        
      </div>
      <div className={styles.main}>
        
      </div> */}
    </div>
  )
}