import Head from 'next/head'
import Image from 'next/image'
// import styles from '../styles/Home.module.css'
import styles from '../styles/Login.module.css'

export default function Login() {
    return (
      <div className={styles.container}>
        <Head>
          <title>Login</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/critiquehall.png" />
        </Head>
  
        <main className={styles.main}>
  
        
            <form id="login">
                <input placeholder="Username" type="text"/>
                <br/>
                <input placeholder="Password" type="password"/>
                <br/>
                <button type="button" className={styles.login_button}>Login</button>
            </form>
  
          
          
        </main>

      </div>
    )
  }