import Head from 'next/head'
import Image from 'next/image'
// import styles from '../styles/Home.module.css'
import styles from '../styles/Login.module.css'
import { css, cx } from '@emotion/react'
import { motion } from "framer-motion"

export default function Login() {
    return (
      <div className={styles.container} >
        <Head>
          <title>Login</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/critiquehall.png" />
        </Head>
  
        <motion.main className={styles.main} 
          animate = {{y: 0 , opacity: 1}}
          initial = {{y: -70, opacity: 0}}
          transition ={{duration: .7}}
          >
  

            <form id="login">
                <input placeholder="Username" className={styles.input_box} type="text"/>
                <br/>
                <input placeholder="Password" className={styles.input_box} type="password"/>
                <br/>
                <button type="button" className={styles.login_button}>Login</button>
            </form>

        </motion.main>

      </div>
    )
  }