import Head from 'next/head'
import Image from 'next/image'
// import styles from '../styles/Home.module.css'
import styles from '../styles/Register.module.css'
import { css, cx } from '@emotion/react'
import { motion } from "framer-motion"
import Home from './home'
import Link from 'next/link'
import Logo from '../public/critiquehall2.png'
import { Heading } from '@chakra-ui/react'
import { Box } from "@chakra-ui/react"

export default function Register() {
    return (
      <div className={styles.container}>
        <Head>
          <title>Register to Critique Hall</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/logo256.png" onLoad=""/>
        </Head>
  

        <motion.main className={styles.main} 
          animate = {{opacity: 1}}
          initial = {{opacity: 0}}
          transition ={{duration: .7}}
          >

            <div className={styles.logo}>
            <Link href="/"><Image src={Logo}></Image></Link>
            </div>
            <Heading mb={4} as="h2" size="lg">Register</Heading>
            <form id="login">
                <input placeholder="First Name" type="text" className={styles.input_box}/>
                <br/>
                <input placeholder="Last Name" type="text" className={styles.input_box}/>
                <br/>
                <input placeholder="Email" type="email" className={styles.input_box}/>
                <br/>
                <input placeholder="Display Name" type="text" className={styles.input_box}/>
                <br/>
                <input placeholder="Password" type="password" className={styles.input_box}/>
                <br/>
                <input placeholder="Confirm Password" type="password" className={styles.input_box}/>
                <br/>
                <button type="button" className={styles.login_button}>Register</button>
            </form>

            <p className={styles.register}>
              <p><Link href="./login"><a>Back to Login</a></Link></p>
            </p>
  
          
      </motion.main>

      </div>
    )
  }