import Head from 'next/head'
import Image from 'next/image'
import { css, cx } from '@emotion/react'
import { motion } from "framer-motion"
import { Center, Grid, GridItem } from "@chakra-ui/react"
import { Heading } from "@chakra-ui/react"
import { Box } from "@chakra-ui/react"
import Link from 'next/link'
import styles from "@styles/Hall.module.css";
import { extendTheme } from '@chakra-ui/react'
import { createBreakpoints } from '@chakra-ui/theme-tools'
import { Button, ButtonGroup } from "@chakra-ui/react"
import {
    Modal,
    ModalOverlay,
    ModalContent,
    ModalHeader,
    ModalFooter,
    ModalBody,
    ModalCloseButton,
  } from "@chakra-ui/react"
import CreatePost from '@component/post/create-post'
import { ChevronDownIcon } from '@chakra-ui/icons'
import {
    Menu,
    MenuButton,
    MenuList,
    MenuItem,
    MenuItemOption,
    MenuGroup,
    MenuOptionGroup,
    MenuIcon,
    MenuCommand,
    MenuDivider,
  } from '@chakra-ui/react'
import { Spacer } from '@chakra-ui/react'
import Pagination from 'react-js-pagination'
import CritiqueList from '@component/CritiqueList'
import { Text } from '@chakra-ui/react'


const breakpoints = createBreakpoints({
    sm: '320px',
    md: '768px',
    lg: '960px',
    xl: '1200px',
    '2xl': '1536px',
  })

const theme = extendTheme({ breakpoints })

export default function HallPage(){
    return(
        <>
        <main className={styles.container}>
            <Head>
            <title>Critique</title>
            <meta name="description" content="Critique Hall generated by Next App" />
            <link rel="icon" href="/logo256.png" onLoad=""/>
            </Head>
            <Box w={{lg: "70%" , sm: '100%'}} mb="5" mx="auto" p="4" mt="14vh" spacing="10" h="10vh" top={0} bg="blue.400">
                <Center><Heading size="2xl" align="center" mt="2" mb="4" color="white">Halls</Heading></Center>
            </Box>
            
            {/* Halls */}
            <Box mt="3vh" w="70%" display={{lg: 'flex', md: 'flex', sm: 'none'}} mx="auto" mb="" top="0">
                <Box w="20vh" h="10vh" ml={{lg: 0, sm: 0}} bg="purple" rounded="lg">
                    <Center>
                    <Text fontSize="3xl" color="white" mt="5" textShadow="1px 1px #000">Technology</Text>
                    </Center>
                    <Center>
                        <Heading size="xs" color="white" mt="1" textShadow="1px 1px #000">Post: 50</Heading>
                    </Center>
                    
                </Box>
                <Spacer />

                <Box w="20vh" h="10vh" ml={{lg: 20, sm: 0}} bg="blue.300" rounded="lg">
                    <Center>
                    <Text fontSize="3xl" color="white" mt="5" textShadow="1px 1px #000">Arts</Text>
                        
                    </Center>
                    <Center>
                        <Heading size="xs" color="white" mt="1" textShadow="1px 1px #000">Post: 50</Heading>
                    </Center>
                    
                </Box>
                <Spacer />
                <Box w="20vh" h="10vh" ml={{lg: 20, sm: 0}} bg="red" rounded="lg">
                    <Center>
                    <Text fontSize="3xl" color="white" mt="5" textShadow="1px 1px #000">Business</Text>
                    </Center>
                    <Center>
                        <Heading size="xs" color="white" mt="1" textShadow="1px 1px #000">Post: 50</Heading>
                    </Center>
                </Box>
                <Spacer />
                <Box w="20vh" h="10vh" ml={{lg: 20, sm: 0}} bg="green.300" rounded="lg">
                    <Center>
                    <Text fontSize="3xl" color="white" mt="5" textShadow="1px 1px #000">Lounge</Text>
                    </Center>
                    <Center>
                        <Heading size="xs" color="white" mt="1" textShadow="1px 1px #000">Post: 50</Heading>
                    </Center>
                </Box>
            </Box>

            <Box mt="3" w="100%" borderColor="gray" position='static' bg="light" border="1px solid gray" borderRadius="md" display={{lg: 'none', md: 'none', sm: 'block'}}>
                <Menu position='static'>
                    <MenuButton
                        px={4}
                        py={2}
                        transition='all 0.2s'
                        w="100%"
                    >          
                    Technology 
                    </MenuButton>
                    <MenuList w="100%" position='static'>
                        <MenuItem>Business</MenuItem>
                        <MenuItem>Design</MenuItem>
                        <MenuItem>Technoloogy</MenuItem>
                        <MenuItem>Lounge</MenuItem>
                    </MenuList>
                </Menu>
            </Box>

            <Box w={{lg: "70%", sm: "100%"}} mt="5" display="flex">
            {/* <Pagination></Pagination> */}
            <Box w="50%"></Box>
            <Spacer />
            <CreatePost />
            </Box>
            <Box w="100%" h="100%" spacing="10px" mt="2">
                <Box w={{lg: "70%" , sm: '100%'}} h="full" mx="auto" p="3" spacing="10" overflow="hidden">
                    {/* Critique Item */}
                    <Box w="100%" display={{lg: 'flex', sm: 'block'}} mt='2ch' borderColor='white' border='1px solid'>
                        <Box p="3" w="100%" bg="light">
                            Hall
                        </Box>
                        <Box p="3" w="100%" bg="light">
                            Image
                        </Box>
                        <Box p="3" w="100%" bg="light">
                            Title
                        </Box>
                        <Box p="3" w="100%" bg="light">
                            Posted by:
                        </Box>
                        <Box p="3" w="100%" bg="light" display='flex'>
                            <Box w="100%" bg="light">
                                Time
                            </Box>
                            <Box w="100%" bg="light">
                                Options
                            </Box>      
                        </Box>                 
                    </Box>
                    {/* Critique Item */}
                    <Box w="100%" display={{lg: 'flex', sm: 'block'}} mt='2ch'  borderColor='white' border='1px solid'>
                        <Box p="3" w="100%" bg="light">
                            Hall
                        </Box>
                        <Box p="3" w="100%" bg="light">
                            Image
                        </Box>
                        <Box p="3" w="100%" bg="light">
                            Title
                        </Box>
                        <Box p="3" w="100%" bg="light">
                            Posted by:
                        </Box>
                        <Box p="3" w="100%" bg="light" display='flex'>
                            <Box w="100%" bg="light">
                                Time
                            </Box>
                            <Box w="100%" bg="light">
                                Options
                            </Box>      
                        </Box>                 
                    </Box>
                    {/* Critique Item */}
                    <Box w="100%" display={{lg: 'flex', sm: 'block'}} mt='2ch'  borderColor='white' border='1px solid'>
                        <Box p="3" w="100%" bg="light">
                            Hall
                        </Box>
                        <Box p="3" w="100%" bg="light">
                            Image
                        </Box>
                        <Box p="3" w="100%" bg="light">
                            Title
                        </Box>
                        <Box p="3" w="100%" bg="light">
                            Posted by:
                        </Box>
                        <Box p="3" w="100%" bg="light" display='flex'>
                            <Box w="100%" bg="light">
                                Time
                            </Box>
                            <Box w="100%" bg="light">
                                Options
                            </Box>      
                        </Box>                 
                    </Box>
                    
                    


                </Box>
            </Box>

        </main>

        
        
        </>
    )
}