import Head from 'next/head'
import Image from 'next/image'
import { css, cx } from '@emotion/react'
import { motion } from "framer-motion"
import { Grid, GridItem } from "@chakra-ui/react"
import { Heading } from "@chakra-ui/react"
import { Box } from "@chakra-ui/react"
import Link from 'next/link'
import styles from "@styles/Hall.module.css";
import { extendTheme } from '@chakra-ui/react'
import { createBreakpoints } from '@chakra-ui/theme-tools'
import { Button, ButtonGroup } from "@chakra-ui/react"
import {
    Modal,
    ModalOverlay,
    ModalContent,
    ModalHeader,
    ModalFooter,
    ModalBody,
    ModalCloseButton,
  } from "@chakra-ui/react"
import CreatePost from '@component/create-post'
import { ChevronDownIcon } from '@chakra-ui/icons'
import {
    Menu,
    MenuButton,
    MenuList,
    MenuItem,
    MenuItemOption,
    MenuGroup,
    MenuOptionGroup,
    MenuIcon,
    MenuCommand,
    MenuDivider,
  } from '@chakra-ui/react'
import { Spacer } from '@chakra-ui/react'

const breakpoints = createBreakpoints({
    sm: '320px',
    md: '768px',
    lg: '960px',
    xl: '1200px',
    '2xl': '1536px',
  })

const theme = extendTheme({ breakpoints })

export default function HallPage(){
    return(
        <>
        <main className={styles.container}>
            <Head>
            <title>Critique</title>
            <meta name="description" content="Critique Hall generated by Next App" />
            <link rel="icon" href="/logo256.png" onLoad=""/>
            </Head>
            <Box w={{lg: "70%" , sm: '100%'}} mb="5" display="flex" mx="auto" p="3" spacing="10">
                        <Heading size="lg">Critiques</Heading>
                        <Spacer />
                        <button className={styles.cpbutton}><Link href='/create-post' as="/create-post">Create Post</Link></button>
            </Box>

            <Box w="100%" h="100%" spacing="10px" mt="5">
                <Box w={{lg: "70%" , sm: '100%'}} bg="white" h="full" mx="auto" p="3" boxShadow="lg" spacing="10" overflow="hidden">
                    <Box display={{lg: 'block' , md: 'block',sm: 'none'}}  >
                        <button className={styles.button1}>All</button>
                        <button className={styles.button2}>Business</button>
                        <button className={styles.button3}>Design</button>
                        <button className={styles.button4}>Technology</button>
                        <button className={styles.button5}>Lounge</button>
                    </Box>

                    <Box mt="3" w="200px" borderColor="gray" border="1px solid gray" borderRadius="md" display={{lg: 'none', md: 'none', sm: 'block'}}>
                        <Menu>
                            <MenuButton
                                px={4}
                                py={2}
                                transition='all 0.2s'
                                w="200px"
                                // borderRadius='md'
                                // borderWidth='1px'
                                // _hover={{ bg: 'gray.400' }}
                                // _expanded={{ bg: 'blue.400' }}
                                // _focus={{ boxShadow: 'outline' }}
                            >
                                
                                All 

                                {/* <ChevronDownIcon /> */}
                            </MenuButton>
                            <MenuList>
                                <MenuItem>All</MenuItem>
                                <MenuItem>Business</MenuItem>
                                <MenuItem>Design</MenuItem>
                                <MenuItem>Technoloogy</MenuItem>
                                <MenuItem>Lounge</MenuItem>
                            </MenuList>
                        </Menu>
                    </Box>


                </Box>
            </Box>

        </main>

        
        
        </>
    )
}