import Head from 'next/head'
import Image from 'next/image'
import { css, cx } from '@emotion/react'
import { motion } from "framer-motion"
import {
    FormControl,
    FormLabel,
    FormErrorMessage,
    FormHelperText,
    Textarea,
    Button,
    Center,
  } from "@chakra-ui/react"
import { Heading } from "@chakra-ui/react"
import { Box } from "@chakra-ui/react"
import Link from 'next/link'
import styles from "@styles/Feedback.module.css";
import { extendTheme } from '@chakra-ui/react'
import { createBreakpoints } from '@chakra-ui/theme-tools'
import { Radio, RadioGroup } from '@chakra-ui/react'
import { useState, useEffect } from 'react';
import { Stack } from '@chakra-ui/react'
import axios from 'axios'
import { useCookies } from 'react-cookie'


const breakpoints = createBreakpoints({
    sm: '320px',
    md: '768px',
    lg: '960px',
    xl: '1200px',
    '2xl': '1536px',
  })

const theme = extendTheme({ breakpoints })

export default function FeedbackPage(){
    const { API_URL } = process.env
    const { API_KEY } = process.env

    // const ans1, ans2, ans3, ans4 = useState('')

    const[ans1, setAns1] = useState(0)
    const[ans2, setAns2] = useState(0)
    const[ans3, setAns3] = useState(0)
    const[ans4, setAns4] = useState(0)
    const[feedback, setFeedback] = useState('')
    const [cookie, setCookies] = useCookies('token', 'encrypte_id')

    const config = {
        headers: { 
          'content-type': 'multipart/form-data',
          'X-API-KEY': `${API_KEY}`,
          'Authorization': 'Basic Y2Fwc3RvbmUyMDIxOjEyMzQ=',
          // 'Accept-Encoding': 'gzip, deflate, br',
          'Accept': 'application/json',
          'token': cookie.token,
          'user_id': cookie.encrypted_id
        }
    }

    const SubmitFeedback = async() =>{
        let formData = new FormData;
        formData.append('answer_1', ans1)
        formData.append('answer_2', ans2)
        formData.append('answer_3', ans3)
        formData.append('answer_4', ans4)
        formData.append('body', feedback)


        axios.post(`${API_URL}/api/feedback`, formData, config)
        .then((response)=>{
            console.log(response.data)
        }).catch((error)=>{
            console.log(error)
        })
    }

    return(
        <main className={styles.container}>
            <Head>
            <title>Critique Hall | Feedback</title>
            <meta name="description" content="Critique Hall generated by Next App" />
            <link rel="icon" href="/logo256.png" onLoad=""/>
            </Head>

            <Box top="0" h="100%" mx="auto" mt="14vh">
                <Heading size="2xl" align="center">WE'D LOVE TO HEAR FROM YOU!</Heading>
                <Heading size="md" align="center" mt="5">Send your feedbacks and suggestions and we'll answer it for you.</Heading>
            </Box>

            <Box display={{lg: "flex", sm: 'block'}} w="95%" bg="blue.700" spacing="10px" top="0" h={{lg: "80vh", sm: "100%"}} mb="5vh" mt="10" py="10">
                <Box w={{lg: "40%" , sm: '100%'}} mx="auto" h="70vh" p="6" color='white'>
                    <form action='' method='POST'>
                    <Heading color="white" mx="auto">Feedback</Heading>
                    <Box mt="5vh" display='flex'>
                        <FormLabel >Duis amet dolor sint sunt minim proident do ullamco cillum ea do.</FormLabel>
                        <RadioGroup onChange={(e)=>setAns1(e.target.value)}>
                        <Stack direction='row'>
                            <Radio value='1'></Radio>
                            <Radio value='2'></Radio>
                            <Radio value='3'></Radio>
                            <Radio value='4'></Radio>
                        </Stack>
                        </RadioGroup>
                    </Box>

                    <Box mt="5vh" display='flex'>
                        <FormLabel>Duis amet dolor sint sunt minim proident do ullamco cillum ea do.</FormLabel>
                        <RadioGroup onChange={(e)=>setAns2(e.target.value)}>
                        <Stack direction='row'>
                            <Radio value='1'></Radio>
                            <Radio value='2'></Radio>
                            <Radio value='3'></Radio>
                            <Radio value='4'></Radio>
                        </Stack>
                        </RadioGroup>
                    </Box>

                    <Box mt="5vh" display='flex'>
                        <FormLabel>Duis amet dolor sint sunt minim proident do ullamco cillum ea do.</FormLabel>
                        <RadioGroup onChange={(e)=>setAns3(e.target.value)}>
                        <Stack direction='row'>
                            <Radio value='1'></Radio>
                            <Radio value='2'></Radio>
                            <Radio value='3'></Radio>
                            <Radio value='4'></Radio>
                        </Stack>
                        </RadioGroup>
                    </Box>

                    <Box mt="5vh" display='flex'>
                        <FormLabel>Duis amet dolor sint sunt minim proident do ullamco cillum ea do.</FormLabel>
                        <RadioGroup onChange={(e)=>setAns4(e.target.value)}>
                        <Stack direction='row'>
                            <Radio value='1'></Radio>
                            <Radio value='2'></Radio>
                            <Radio value='3'></Radio>
                            <Radio value='4'></Radio>
                        </Stack>
                        </RadioGroup>
                    </Box>

                    <Center><Textarea w="100%" bg="light" mt="5vh" color='black' mx="auto" position='static' onChange={(e)=>setFeedback(e.target.value)}/></Center>

                    <Box w="100%">
                        <Center><Button type='submit' mx='auto' colorScheme='blue' mt="3" onClick={SubmitFeedback}>Submit</Button></Center>
                    </Box>
                    </form>
                </Box>

                <Box w={{lg: "40%" , sm: '90%'}} mt={{lg: '0', sm: '5vh'}} bg="white" mx="auto" h="70vh" p="3" boxShadow="lg" borderRadius="lg">
                    <Center><Heading mx="auto">Contact Information</Heading></Center>
                    
                    
                </Box>
            </Box>
        </main>
    )
}

