import Head from 'next/head'
import Image from 'next/image'
import { css, cx } from '@emotion/react'
import { motion } from "framer-motion"
import {
    FormControl,
    FormLabel,
    FormErrorMessage,
    FormHelperText,
    Text,
    Textarea,
    Button,
    Center,
  } from "@chakra-ui/react"
import { Heading } from "@chakra-ui/react"
import { Box } from "@chakra-ui/react"
import Link from 'next/link'
import styles from "@styles/Feedback.module.css";
import { extendTheme, useColorModeValue } from '@chakra-ui/react'
import { createBreakpoints } from '@chakra-ui/theme-tools'
import { Radio, RadioGroup } from '@chakra-ui/react'
import { useState, useEffect } from 'react';
import { Stack } from '@chakra-ui/react'
import axios from 'axios'
import { useCookies } from 'react-cookie'


const breakpoints = createBreakpoints({
    sm: '320px',
    md: '768px',
    lg: '960px',
    xl: '1200px',
    '2xl': '1536px',
  })

const theme = extendTheme({ breakpoints })

export default function FeedbackPage(){
    const { API_URL } = process.env
    const { API_KEY } = process.env

    // const ans1, ans2, ans3, ans4 = useState('')

    const[ans1, setAns1] = useState(0)
    const[ans2, setAns2] = useState(0)
    const[ans3, setAns3] = useState(0)
    const[ans4, setAns4] = useState(0)
    const[feedback, setFeedback] = useState('')
    const [cookie, setCookies] = useCookies('token', 'encrypte_id')

    const config = {
        headers: { 
          'content-type': 'multipart/form-data',
          'X-API-KEY': `${API_KEY}`,
          'Authorization': 'Basic Y2Fwc3RvbmUyMDIxOjEyMzQ=',
          // 'Accept-Encoding': 'gzip, deflate, br',
          'Accept': 'application/json',
          'token': cookie.token,
          'user_id': cookie.encrypted_id
        }
    }

    const SubmitFeedback = async() =>{
        let formData = new FormData;
        formData.append('answer_1', ans1)
        formData.append('answer_2', ans2)
        formData.append('answer_3', ans3)
        formData.append('answer_4', ans4)
        formData.append('body', feedback)


        axios.post(`${API_URL}/api/feedback`, formData, config)
        .then((response)=>{
            console.log(response.data)
        }).catch((error)=>{
            console.log(error)
        })
    }

    return(
        <main className={useColorModeValue(styles.container, styles.container2)}>
            <Head>
            <title>Critique Hall | Feedback</title>
            <meta name="description" content="Critique Hall generated by Next App" />
            <link rel="icon" href={useColorModeValue('logo256.png', 'logo256-dark.png')} onLoad=""/>
            <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@700&display=swap" rel="stylesheet" />
            </Head>

            <Box top="0" h="100%" mx="auto" mt="14vh">
                <Heading fontFamily={'Raleway'} color={useColorModeValue('#1B1464', '#B2A3FF')} size="2xl" align="center">WE&apos;D LOVE TO HEAR FROM YOU!</Heading>
                <Heading fontFamily={'Raleway'} color={useColorModeValue('#1B1464', '#B2A3FF')} size="md" align="center" mt="5">Send your feedbacks and suggestions and we&apos;ll answer it for you.</Heading>
            </Box>

            <Box bgImage={'discussions.png'} bgSize={'60em'} bgPosition={'right'} bgRepeat={'no-repeat'} display={{lg: "flex", sm: 'block'}} w="90%" className={useColorModeValue(styles.box_light, styles.box_dark)} spacing="10px" top="0" h={{lg: "70vh", sm: "100%"}} mb="5vh" mt="10" py="10">
                <Box w={{lg: "40%" , sm: '100%'}} mx="auto" h="70vh" p="6" color='white'>
                    <form action='' method='POST'>
                    {/* <Heading color="white" mx="auto">Feedback</Heading> */}
                    <Box mt="5vh" display='flex'>
                        <FormLabel >Duis amet dolor sint sunt minim proident do ullamco cillum ea do.</FormLabel>
                        <RadioGroup onChange={(e)=>setAns1(e.target.value)}>
                        <Stack direction='row'>
                            <Radio value='1'></Radio>
                            <Radio value='2'></Radio>
                            <Radio value='3'></Radio>
                            <Radio value='4'></Radio>
                        </Stack>
                        </RadioGroup>
                    </Box>

                    <Box mt="5vh" display='flex'>
                        <FormLabel>Duis amet dolor sint sunt minim proident do ullamco cillum ea do.</FormLabel>
                        <RadioGroup onChange={(e)=>setAns2(e.target.value)}>
                        <Stack direction='row'>
                            <Radio value='1'></Radio>
                            <Radio value='2'></Radio>
                            <Radio value='3'></Radio>
                            <Radio value='4'></Radio>
                        </Stack>
                        </RadioGroup>
                    </Box>

                    <Box mt="5vh" display='flex'>
                        <FormLabel>Duis amet dolor sint sunt minim proident do ullamco cillum ea do.</FormLabel>
                        <RadioGroup onChange={(e)=>setAns3(e.target.value)}>
                        <Stack direction='row'>
                            <Radio value='1'></Radio>
                            <Radio value='2'></Radio>
                            <Radio value='3'></Radio>
                            <Radio value='4'></Radio>
                        </Stack>
                        </RadioGroup>
                    </Box>

                    <Box mt="5vh" display='flex'>
                        <FormLabel>Duis amet dolor sint sunt minim proident do ullamco cillum ea do.</FormLabel>
                        <RadioGroup onChange={(e)=>setAns4(e.target.value)}>
                        <Stack direction='row'>
                            <Radio value='1'></Radio>
                            <Radio value='2'></Radio>
                            <Radio value='3'></Radio>
                            <Radio value='4'></Radio>
                        </Stack>
                        </RadioGroup>
                    </Box>

                    <Center><Textarea bgColor={useColorModeValue('#FFFFFF','#2E2E2E')} color={useColorModeValue('#000000', '#FFFFFF')} fontFamily={'Raleway'} fontWeight={'extrabold'} placeholder='Message...' w="100%"  mt="5vh" mx="auto" position='static' onChange={(e)=>setFeedback(e.target.value)}/></Center>

                    <Box w="100%">
                        <Center><Button size={'lg'} type='submit' mx='auto' bgColor={useColorModeValue('#2777C1','#0085FF')} color={useColorModeValue('#FFFFFF', '#FFFFFF')} _hover={{bgColor: 'blue'}} mt="3" onClick={SubmitFeedback}>SUBMIT</Button></Center>
                    </Box>
                    </form>
                </Box>

                <Box w={{lg: "40%" , sm: '90%'}} mt={{lg: '0', sm: '5vh'}} bgColor={useColorModeValue('#FFFFFF','#2E2E2E')} mx="auto" h={{lg: '50vh', md: '55vh', sm: '60vh'}} p="3" boxShadow="lg" borderRadius="lg">
                    <Center><Heading fontFamily={'Raleway'} fontWeight={'extrabold'} color={useColorModeValue('#C1272D', '#FF5C61')} mx="auto">Contact Information</Heading></Center>
                    <Box bgColor={useColorModeValue('#FFFFFF','#2E2E2E')} w={{lg: "90%" , sm: '90%'}} mt={{lg: '0vh', md: '2vh', sm: '2vh'}}  mx="auto" h="20vh" p="3">
                    <br />
                    <Center><Text fontSize='2xl' fontWeight={'bold'} color={useColorModeValue('#29226E', '#B2A3FF')}> Azariah Danizar G. Concepcion</Text></Center>
                    <Center><Text fontSize='md' fontWeight={'bold'} fontStyle={'italic'} color={useColorModeValue('#BF7604', '#FFA10F')}> Full-Stack Developer | 201801130@iacademy.edu.ph | (+63) 949-846-0846</Text></Center>
                    <br />
                    <Center><Text fontSize='2xl' fontWeight={'bold'} color={useColorModeValue('#29226E', '#B2A3FF')}> Jomari L. Matias</Text></Center>
                    <Center><Text fontSize='sm' fontWeight={'bold'} fontStyle={'italic'} color={useColorModeValue('#BF7604', '#FFA10F')}> UX Designer / Content Manager | 201801253@iacademy.edu.ph | (+63) 998-084-4162</Text></Center>
                    <br />
                    <Center><Text fontSize='2xl' fontWeight={'bold'} color={useColorModeValue('#29226E', '#B2A3FF')}> Richie Gene R. Tan</Text></Center>
                    <Center><Text fontSize='sm' fontWeight={'bold'} fontStyle={'italic'} color={useColorModeValue('#BF7604', '#FFA10F')}> Full-Stack Developer / Creative Director | 201801273@iacademy.edu.ph | (+63) 916-424-9531</Text></Center>
                    <br />
                    <Center><Text fontSize='2xl' fontWeight={'bold'} color={useColorModeValue('#29226E', '#B2A3FF')}> Jose Luis P. Tandayu</Text></Center>
                    <Center><Text fontSize='md' fontWeight={'bold'} fontStyle={'italic'} color={useColorModeValue('#BF7604', '#FFA10F')}> Full-Stack Developer | 201801312@iacademy.edu.ph | (+63) 916-418-7235</Text></Center>
                    </Box> 
                </Box>
            </Box>
        </main>
    )
}

